-- Store vouchers generated by the Omada Northbound Open API on the payment.
ALTER TABLE payment_transactions
  ADD COLUMN IF NOT EXISTS omada_voucher_group_id TEXT,
  ADD COLUMN IF NOT EXISTS voucher_code TEXT;

ALTER TABLE portal_sessions
  ADD COLUMN IF NOT EXISTS portal_auth_url TEXT;

CREATE INDEX IF NOT EXISTS idx_transactions_voucher_code
  ON payment_transactions (voucher_code)
  WHERE voucher_code IS NOT NULL;
